---
name: 'MLibrary Deploy to Kubernetes Cluster'
description: 'Deploys an image to a Kubernetes Cluster'
inputs:
  registry:
    description: Registry to log into
    default: ghcr.io
  registry_username:
    description: Username to log into the registry with
    default: ${{ github.actor }}
  registry_token:
    decription: Token to log into the registry with
    required: true
  image:
    description: Image to deploy, e.g. registry/organization/image_name:tag
    required: true
  cluster_ca:
    description: The Kubernetes cluster CA certificate, base64-encoded
    required: true
  cluster_server:
    description: The Kubernetes server API endpoint
    required: true
  namespace_token:
    description: A base64-encoded Kubernetes service account token
    required: true
  namespace:
    description: The Kubernetes namespace to deploy to
    required: true
  type:
    description: Any resource type, comma-separated set of resource types, or 'all'
    default: 'deployment'
  resource:
    description: >-
      Name of the resource whose image to set, a label selector like "--selector='app=someapp'", or "--all"
    default: 'web'
  container:
    description: >-
      The container in the resource whose image to set, or "*" for all containers
    default: 'web'

runs:
  using: "composite"
  steps:
    - name: Log into container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_token }}
    - name: Check that the image & tag exist
      run: docker manifest inspect "$IMAGE" > /dev/null
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
    - uses: azure/setup-kubectl@v1
    - name: Authenticate with kubernetes
      shell: bash
      run: |
        mkdir -p ${HOME}/.kube/certs/cluster
        echo ${{ inputs.cluster_ca }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
        kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server="$CLUSTER_SERVER"
        kubectl config set-credentials default --token=$(echo "$NAMESPACE_TOKEN" | base64 -d)
        kubectl config set-context default --cluster=cluster --user=default --namespace="$NAMESPACE"
        kubectl config use-context default
      env:
        CLUSTER_CA: ${{ inputs.cluster_ca }}
        CLUSTER_SERVER: ${{ inputs.cluster_server }}
        NAMESPACE_TOKEN: ${{ inputs.namespace_token }}
        NAMESPACE: ${{ inputs.namespace }}
    - name: Deploy
      shell: bash
      run: |
        kubectl set image "$TYPE" "$RESOURCE" "$CONTAINER=$IMAGE"
      env:
        TYPE: ${{ inputs.type }}
        RESOURCE: ${{ inputs.resource }}
        CONTAINER: ${{ inputs.container }}
        IMAGE: ${{ inputs.image }}
